### ISSUE TITLE
phar version?

### ISSUE THREAD

**Issue by morrow95** [snowplow/referer-parser#83] opened 2014-09-16 16:35 UTC
Can someone with time create a phar version or do a pull request of one using box?  This is above my head, but I cannot use without having a phar... would be extremely grateful if anyone has the time.

http://box-project.org/

**Comment by morrow95** [comment] 2015-02-10 11:10
Requesting the phar version again @lstrojny  Really want to incorporate this in a project, but as I've said before I do not have the means to use composer and anything I have found to create a phar version requires composer to create it.

**Comment by morrow95** [comment] 2015-05-03 21:34
+1

**Comment by lstrojny** [comment] 2015-06-12 12:19
Duplicate of #78

**Closed by lstrojny** 2015-06-12 12:19 UTC
